#.github/workflows/deployment-action.yml
on:
  push:
    branches:
    - main



jobs:
  deployQA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Salesforce CLI
        run: |
          npm install sfdx-cli
          node_modules/sfdx-cli/bin/run --version
		  node_modules/sfdx-cli/bin/run plugins --core
          pip install xq
          pip install yq
      - name: Install sfdxGit delta
        run: |
          echo y | sfdx plugins:install sfdx-git-delta
          sfdx sgd:source:delta --to "HEAD" --from "HEAD^"  --ignore ignorefile --output "."
          cat package/package.xml
	  - name: Authenticate DevHub

	    run: |
		  echo "${SALESFORCE_JWT_SECRET_KEY}" > server.key
		  node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_DEVHUB_USERNAME}} --setdefaultdevhubusername -a devhub
	    env:
		  SALESFORCE_JWT_SECRET_KEY: ${{ secrets.SALESFORCE_JWT_SECRET_KEY }}



      - name: 'Running checks'
        run: |
          sfdx force:source:deploy -x  package/package.xml --checkonly  -l 'RunLocalTests'  -u devhub 
