#.github/workflows/deployment-action.yml


on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #Checkout target branch (Main in this example)
    - uses: actions/checkout@v2 
    
    #Install node
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        check-latest: true

    - name: Install Salesforce CLI  
    #Install all dependancies for Salesforce - SFDX CLI
      run: |
        # Hide npm warning messages - for readability
        export npm_config_loglevel=silent
        npm install sfdx-cli
        node_modules/sfdx-cli/bin/run --version
        node_modules/sfdx-cli/bin/run plugins --core
      
    - name: Authenticate DevHub  #Authenticate against production (In this example alias prod to devhub)
      run: |
        echo "${SALESFORCE_JWT_SECRET_KEY}" > server.key
        node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_DEVHUB_USERNAME}} --setdefaultdevhubusername -a devhub
      env:
        SALESFORCE_JWT_SECRET_KEY: ${{ secrets.SALESFORCE_JWT_SECRET_KEY }}
      
    - name: Deploy Source to target org 
    # Deployment Script - deploy the force-app folder to the target org
      run:  node_modules/sfdx-cli/bin/run force:source:deploy -u devhub -p ./force-app 
